### ISSUE TITLE
Lagging on scroll list

### ISSUE THREAD

**Issue by do-web** [thenikso/angular-inview#61]
I have a long list, if i scroll the list the list is lagging. The in view attr is on all list items.

**Comment by clementlamoureux** [comment]
+1

**Comment by thenikso** [comment]
Well if the list is very long maybe this is not the proper directive. Maybe something like this https://github.com/sroze/ngInfiniteScroll would be more appropriated.

In general, having too many `inview` on items might make the scrolling laggy because the `scroll` event on the window will trigger a handler that will then have to do a lot of work. The best solution is to have fewer `inview` elements
