### ISSUE TITLE
Call inview only if/when window is in focus.

### ISSUE THREAD

**Issue by trnelson** [thenikso/angular-inview#66]
Is it possible (or can it be :smile:) to call `windowCheckInView` manually from the scope or root scope? Or otherwise only do an inview check when window is in focus?

The main thing I'm trying to do is defer the inview directive from firing while the window is out of focus, and to do an inview check when the window is in focus. I'm using `$window.onfocus` to check this.

Any ideas? My initial idea was to just force inview to check on focus, but would appreciate input.

Thanks!

**Comment by trnelson** [comment]
Leaving this here, but I was able to achieve this by essentially using inview to "flag" items as read, but not actually process them (I maintained an array to track them).

Then when the page was in view, I could loop through the array and process the items.

This worked just fine for me, though it took a bit of thought to get it working. Might be nice to offer the ability to process inview only if the window is active. Either way, thanks for a great tool!

**Comment by thenikso** [comment]
Glad to know that you solved the problem! 

Having inview only be active when the window is on focus might be an idea but then you'd need to to this as a per-directive-usage basis (ie in the in-view-options). It might make sense but if the problem is otherwise solvable as you did without complicating the directive it doesn't sound so urgent.

Lets see if this issue get some +1s
