### ISSUE TITLE
inViewContainer is incompatible with inViewOptions: debounce

### ISSUE THREAD

**Issue by onemanclapping** [thenikso/angular-inview#84]
Try something like:
```
<div in-view-container>
    <div in-view="doSomething($inview)" in-view-options="{debounce: 2000}"></div>
    ...
    <div in-view="doSomething($inview)" in-view-options="{debounce: 2000}"></div>
</div>
```
And you'll see that the $inView is no longer relative to the container but the viewport.

A quick debugging showed me that inViewContainerController.checkInView is no longer called after adding a debounce.

Probably there's something wrong here, although I can't really read this code :x
```
performCheck = (ref = (ref1 = item.customDebouncedCheck) != null ? ref1 : containerController != null ? containerController.checkInView : void 0) != null ? ref : windowCheckInView;
```

I'll try to update this if I find a solution but if you can solve this faster, kudos! :)

**Comment by ScottSpittle** [comment]
I skipped over in-view-container and added an additional option, the ID of the element your in-view is within, then use that height instead of the window height.

**Comment by maxilev** [comment]
I've met similar issue when used `in-view-container` together with `debounce`, and I figured out what is the problem. When we use debounce it creates custom handler here: https://github.com/thenikso/angular-inview/blob/master/angular-inview.coffee#L54, after event happens we call this function here: https://github.com/thenikso/angular-inview/blob/master/angular-inview.coffee#L84. But the problem is that `customDebouncedCheck` uses `element[0]` as a container, so it's not what we are expecting.

**Comment by thenikso** [comment]
I reviewed the PR and it seamed legit. @maxilev would you be so kind to see if the same problem is in v2 as well? See #107

Thanks!
