### ISSUE TITLE
Does not trigger while user is dragging scroll bar

### ISSUE THREAD

**Issue by mattdeckard** [thenikso/angular-inview#98]
If you scroll an element into view by clicking and dragging the scroll bar, the inview expression is not evaluated unless it is in frame at the time the user lets go of the scroll bar.

I am going to try to fix this and submit a pull request later today.

**Comment by mattdeckard** [comment]
Clarification: the issue is that it doesn't trigger while the user is dragging the scrollbar on a scrollable element within the page. It (probably) works for scrolling the full page (although I haven't checked)

**Comment by mattdeckard** [comment]
Whoops, for some reason merging this into my forked repo closed the issue.

**Comment by thenikso** [comment]
If I understood this properly, you mean to add the inview check to `scroll` events of custom elements. 

Instead of doing this within the plugin, one could trigger the `checkInView` event on the window like so `angular.element(window).triggerHandler('checkInView')` inside a custom scroll event handler on any element.
